/**
 * Ações para tela de cadastro de amigo.
 */
const ADD_FRIEND = 'ADD_FRIEND';
const DELETE_FRIEND = 'DELETE_FRIEND';
const UPDATE_FRIEND = 'UPDATE_FRIEND';
const SORTEAR = 'SORTEAR';
const DELETE_ALL = 'DELETE_ALL'
const TOGGLE_SCREEN_SORTED = 'TOGGLE_SCREEN_SORTED'
const TOGGLE_THEME_MODE = 'TOGGLE_THEME_MODE'
/**
 * Ações para o modal.
 */

const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'

export {
    ADD_FRIEND,
    DELETE_FRIEND,
    OPEN_MODAL,
    CLOSE_MODAL,
    UPDATE_FRIEND,
    SORTEAR,
    DELETE_ALL,
    TOGGLE_SCREEN_SORTED,
    TOGGLE_THEME_MODE

}